# Dockerfile.backend
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install

# Bundle app source
COPY . .

# Build the TypeScript code
RUN npm run build

EXPOSE 5000
CMD ["node", "dist/src/server.js"]
