# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the container
COPY ./backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code to the container
COPY ./backend .

# Expose the port that your backend will run on
EXPOSE 4000

# Define the command to start your backend
CMD ["npm", "start"]